[workspace]
resolver = "3"
members = ["chameleos", "chamel"]
default-members = ["chameleos"]

[workspace.dependencies]
interprocess = "2.2.3"
clap = { version = "4.5.48", features = ["derive"] }
csscolorparser = "0.7.2"
