[package]
name = "chameleos"
version = "0.1.2"
authors = ["Thomas Lindae <thomas@lindae.de>"]
edition = "2024"
description = "Screen annotation tool for niri and Hyprland"
repository = "https://github.com/Treeniks/chameleos"
license = "GPL-3.0-or-later"
keywords = ["wayland"]
default-run = "chameleos"

# named differently from the `chameleos` bin target, as sharing the name
# causes a rustdoc output collision (https://github.com/rust-lang/cargo/issues/6313)
[lib]
name = "chameleos_core"

[dependencies]
clap = { version = "4.6.6", features = ["derive"] }
csscolorparser = "0.8.4"

wayland-client = "0.31.15"
# layer shell
wayland-protocols-wlr = { version = "0.3.12", features = ["client"] }
# cursor shape
wayland-protocols = { version = "0.32.13", features = [
  "client",
  "staging",
  "unstable",
] }
# required to get raw window handles
wayland-backend = { version = "0.3.17", features = ["client_system"] }
calloop = "0.14.4"
calloop-wayland-source = "0.4.1"

wgpu = "27.0.1"
raw-window-handle = "0.6.2"
env_logger = "0.11.11"
log = "0.4.34"
pollster = "0.4.0"

lyon = "1.0.19"
bytemuck = "1.25.2"

undoredo = { version = "0.14.1", features = ["derive", "stable-vec"] }
stable-vec = "0.4.3"

[build-dependencies]
chrono = "0.4.45"
